### ISSUE TITLE
About inference time on GPU

### ISSUE THREAD

**Issue by jmliu206** [camlsys/degree-quant#6]
Hello,
Your paper seems to give the int8 model running time on the GPU in table 4, and the time is reduced compared to float32. Does this code describe how to get this time?

I have tested the "val_loss time" in this code, but the FP32 model seems to be faster than the INT8 model.

```python
torch.cuda.synchronize()
s = time.time()
val_loss = eval_loss(model, val_loader)
torch.cuda.synchronize()
e = time.time()
print(e-s)
```

Could you tell me how I should measure the time if my method is wrong?

**Comment by shyam196** [comment]
It depends on the GPU (among many things) + how well optimized your kernels are. In principle you should expect the INT8 version to be the same/slightly faster on GPU, although the difference will be relatively small due to GPUs not relying aggressively on caching.

As far as I'm aware, PyTorch does not support INT8 on GPU at all, so I am unsure how you are measuring the latency? Are you just comparing an FP32 model to a simulated quantized model? To get the speedup, you do actually have to export the weights and use a proper INT8 kernel.
